### ISSUE TITLE
Ubuntu 22.04 doesn't have qt5-default package

### ISSUE THREAD

**Issue by andrewjessop** [c42f/displaz#245]
I was following the Readme to install, but `qt5-default` package doesn't exist in Ubuntu 22.04.

I did find the correct package:
```
ajessop@DESKTOP-AKOGURR:~/repos$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
ajessop@DESKTOP-AKOGURR:~/repos$ sudo apt install libqt5opengl5-dev
```

I'd be happy to submit a PR to update the Readme if you agree.

**Comment by nigels-com** [comment]
Agreed.  The Ubuntu 22.04 docker build _does_ work, but the Readme is out of date.
[docker/ubuntu_22_04/Dockerfile](https://github.com/c42f/displaz/blob/master/docker/ubuntu_22_04/Dockerfile)

`apt install -y g++ cmake qtbase5-dev python3`
