### ISSUE TITLE
QT Socket Issues on Ubuntu 24.04

### ISSUE THREAD

**Issue by BenCurran98** [c42f/displaz#252]
Hi! Firstly, thanks for the package, it's great!
I've recently updated my OS to Ubuntu 24.04 and am trying to rebuild Displaz. I'm able to get through the build fine by following the README instructions, however when I go to launch the application it gives me the following error:

`QSocketNotifier: Can only be used with threads started with QThread`

The window opens but doesn't show the main graphics screen and the logs show an error saying "Failed to initialize GLEW"
![Screenshot from 2024-08-22 15-21-53](https://github.com/user-attachments/assets/23e2eaab-ed90-4480-b6f3-5aec1f7ce974)

I'm not sure what other information you need me to provide, so let me know :)

**Comment by nigels-com** [comment]
Can you try switching your desktop to X11, rather than Wayland?

**Comment by BenCurran98** [comment]
That worked! Thanks for your speedy response :smiley:
