### ISSUE TITLE
problem with RPly

### ISSUE THREAD

**Issue by OmriTreidel** [c42f/displaz#63]
displaz can't load ply files without \n at the end of the file

**Comment by c42f** [comment]
I can't reproduce this - I tried taking an ply file from the test directory (eg, test/polygons.ply) and stripping off the last newline but displaz seems to load it fine.  Can you send a small example?

**Comment by c42f** [comment]
Fixed in b20c11a ... This was a rather obscure bug in rply itself!  I've also fixed it for you on the triangulate-polygons branch.

**Comment by OmriTreidel** [comment]
Cheers.
