### ISSUE TITLE
Windows continuous build

### ISSUE THREAD

**Issue by c42f** [c42f/displaz#66]
Since windows isn't the main development environment, it would be great to have a continuous build set up.  appveyor looks really nice for this and I created an account, but it requires porting to qt5 ( #65 ) unless we want to build qt ourselves.

**Comment by c42f** [comment]
Done in f5a7fa9.

**Comment by c42f** [comment]
@JoshChristie an up to date continuous build for windows is now available!

https://displaz-data.s3.amazonaws.com/builds/ci/latest/displaz-win64.exe

**Comment by JoshChristie** [comment]
Yay ! Thanks Chris :+1:
