### ISSUE TITLE
Remove deprecated OpenGL calls

### ISSUE THREAD

**Issue by c42f** [c42f/displaz#7]
Particularly in the GLSL code, warnings are emitted by the nvidia compiler about using pre-opengl 3 features which are rather annoying.  There's a few other places that deprecated APIs are used as well - should probably fire it up with a non-compatibility context and see what breaks.

**Comment by nigels-com** [comment]
I've got a branch of GLEW intended for core context support.  displaz may serve as a good test for that, but may wind up being a lot of work.

**Comment by nigels-com** [comment]
Oh, this looks like a deal-breaker on Mac OS X (10.9.5)

    QGLShader::compile(Fragment): ERROR: 0:1: '' :  version '130' is not supported
    ERROR: 0:153: 'flat' : syntax error syntax error
    QGLShader::link: "ERROR: Compiled vertex shader was corrupt.
    ERROR: Compiled fragment shader was corrupt. 
    QGLShader::compile(Fragment): ERROR: 0:1: '' :  version '130' is not supported
    QGLShader::compile(Fragment): ERROR: 0:1: '' :  version '130' is not supported

Version 130 would require a core context on a Mac... :-(

**Comment by c42f** [comment]
Actually, I don't think displaz really works reliably on OSX at all.  My impression from @dedalusj was that Qt-4.8+OpenGL is in a bit of a sorry state (and basically out of support) and we'd have to port to Qt-5 which seems nontrivial.  Personally I don't have any apple hardware so I'm a bit useless on this front.

So are you saying that the error above a deal breaker for the *current* version of displaz on OSX?  That doesn't surprise me :-/

**Comment by c42f** [comment]
BTW, I tried asking Qt for a core context on linux (+nvidia GPU) a while back, but it appeared to happily ignore me and pass back a compatibility context.  At that stage I fixed the visible warnings from the driver and went on to other things ;-)

**Comment by nigels-com** [comment]
I think the underlying issue on the Mac is that OpenGL 3+ functionality is only available for core contexts.  The message about GLSL 130 not being supported is consistent with that.

I can focus on this if you think it's a priority to make displaz work on the Mac, but I'd personally rather get a bit more hands-on with the point cloud data and octree.

**Comment by c42f** [comment]
While it'd be great to get this working, I think it could easily blow out to a whole lot of work.  Please choose something else if that's more to your taste.

**Comment by chrisidefix** [comment]
@c42f I'm running into the same issue and I understand this isn't trivial (quick) to solve. I would be interested in getting this up and running, though. However, before I invest any more time - is there any timeline you have in mind before completing the move to Qt5? (I see there is #65 and #72 from July '15, but I assume that's not ready for merging and nobody has bothered again since then.)

**Comment by c42f** [comment]
There's no real timeline - qt5 is mainly relevant to OSX and to enable displaz to eventually use some more modern qt features.  Both of these things would be "nice to have" in a theoretical sense, but nobody I know is telling me they need OSX support.  Personally I don't even have access to an OSX system to test on, so I'm spending my limited time elsewhere at the moment.

If you want to go through and modernize all the old OpenGL stuff, that would be great.  I suspect the offending code is mostly confined to `view3d.cpp` now - you could start by converting `View3D::drawCursor()` for instance.

**Comment by c42f** [comment]
This was done as part of #65
